// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuadraticEquation.EntityFramework;

#nullable disable

namespace QuadraticEquation.EntityFramework.Migrations
{
    [DbContext(typeof(QuadraticEquationDbContext))]
    partial class QuadraticEquationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("QuadraticEquation.EntityFramework.DTOs.QuadraticEquationDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("A")
                        .HasColumnType("REAL");

                    b.Property<double>("B")
                        .HasColumnType("REAL");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("QuadraticEquations");
                });
#pragma warning restore 612, 618
        }
    }
}
